<h1>Статьи</h1>
<a href="/admin/article/add/">Добавить</a><br /><br />
<?php
	$flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
    </button>
    <ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');
    
    echo $flash->render('error',    array('alert', 'alert-dismissable', 'alert-danger'));
    echo $flash->render('info',     array('alert', 'alert-dismissable', 'alert-info'));
    echo $flash->render('default',  array('alert', 'alert-dismissable', 'alert-warning'));
    echo $flash->render('success',  array('alert', 'alert-dismissable', 'alert-success'));
?>
<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>#</th>
            <th>Категория</th>
            <th>Заголовок</th>
            <th>Статья</th>
            <th>Начало статьи</th>
            <th>Опубликовано</th>
            <th>Действие</th>
        </tr>
<?php
foreach ($articles as $item) {
    $category = $item->getCategory();
    if ($category) {
        $catName = $category->getCategoryName();
    } else {
        $catName = '';
    }
    if ($item->getIsPublic()) {
        $isPublic = 'Да';
    } else {
        $isPublic = 'Нет';
    }

    $url = $this->url('blog', array('action' => 'article', 'id' => $item->getId()));
    echo "<tr>
            <td>{$item->getId()}</td>
            <td>{$catName}</td>
            <td>{$item->getTitle()}</td>
            <td><a style=\"color: black;\" href=\"$url\">{$item->getArticleForTable()}</a></td>
            <td><a style=\"color: black;\" href=\"$url\">{$item->getShortArticleForTable()}</a></td>
            <td>{$isPublic}</td>";
            
    echo   '<td><a href="'.$this->url('admin/article', array('action' => 'edit', 'id' => $item->getId())).'">Редактировать</a>&nbsp;&nbsp;
                 <a href="'.$this->url('admin/article', array('action' => 'delete', 'id' => $item->getId())).'" onclick="if (confirm(\'Удалить запись?\')) { document.location = this.href; } return false;">Удалить</a></td>
        </tr>';
}
?>
    </tbody>
</table>

<?php

echo $this->paginationControl($articles,
                                'Sliding',
                                'pagination_control', array('route' => 'admin/article'));
?>